koth_config:
  team_id: "CyberArmy_V10_8"
  target_ip: "10.10.10.5"
  flag_path: "/var/www/html/flag.txt"
  requests_per_sec: 35
credentials:
  ssh_user: "root"
  ssh_pass: "SecurePass2026!"
whitelist_ips:
  - "10.10.14.5"
